name: Clinic Service

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
                             
    env:
      Solution_Name: Margarita_Grafa_PetProject2025.sln  
      
    steps:
    - name: Build and analyze
      run: dotnet build --configuration Debug
